import { TemplateField } from "../interfaces/iTemplateField";

export const glass: TemplateField = {
  id: "glass",
  type: "container",
  label: "Glass",
  countField: 1,
  helpText: "Registrering av glass-specimens",
  layout: "vertical",
  children: [
    {
      id: "glassBlokker",
      type: "container",
      layout: "horizontal", 
      isIndented: false,
      children: [
        {
          id: "glassValue",
          label: "Glass",
          type: "text",
          isIndented: false,
          defaultValue: "",
          helpText: "Angi glass-ID"
        },
        {
          id: "blokker",
          label: "Blokker",
          type: "number",
          isIndented: false,
          defaultValue: 1,
          helpText: "Angi blokk-ID"
        },
      ],
    },
    {
      id: "dimensjoner",
      label: "Dimensjoner",
      type: "container",
      layout: "vertical", 
      isIndented: false,
      helpText: "Angi dimensjoner for glasset",
      children: [
        {
          id: "hoyde",
          label: "Høyde",
          type: "number",
          isIndented: true,
          defaultValue: 0,
          unit: "mm",
          helpText: "Høyde i millimeter"
        },
        {
          id: "bredde",
          label: "Bredde",
          type: "number",
          isIndented: true,
          defaultValue: 0,
          unit: "mm",
          helpText: "Bredde i millimeter"
        },
        {
          id: "lengde",
          label: "Lengde",
          type: "number",
          isIndented: true,
          defaultValue: 0,
          unit: "mm",
          helpText: "Lengde i millimeter"
        },
      ],
    },
    {
      id: "utseende",
      label: "Utseende",
      type: "dropdown",
      defaultValue: "stilket",
      options: ["bredbaset", "stilket", "annet"],
      isIndented: false,
      helpText: "Velg utseende for glasset"
    },
    {
      id: "grynAmount",
      label: "Antall Gryn",
      type: "number",
      defaultValue: 0,
      isIndented: false,
      helpText: "Antall gryn i blokken"
    },
    {
      id: "orientert",
      label: "Orientert",
      type: "checkbox",
      defaultValue: true,
      isIndented: false,
      helpText: "Marker om glasset er orientert"
    },
    {
      id: "oppdeltParent",
      type: "container",
      layout: "horizontal",
      isIndented: false,
      helpText: "Informasjon om oppdeling",
      children: [
        {
          id: "oppdelt",
          label: "Oppdelt",
          type: "checkbox",
          isIndented: false,
          defaultValue: false,
          helpText: "Marker om glasset er oppdelt"
        },
        {
          id: "oppdeltNumber",
          label: "Antall",
          type: "number",
          isIndented: false,
          defaultValue: 0,
          conditionalOn: "oppdelt",
          helpText: "Angi antall oppdelte deler"
        },
      ],
    },
  ],
};

export const hudbit: TemplateField = {
  id: "hudbit",
  label: "Hudbit",
  type: "container",
  layout: "vertical",
  countField: 1,
  isIndented: false,
  helpText: "Registrering av hudbit-specimen",
  children: [
    {
      id: "variant",
      label: "Variant",
      type: "dropdown",
      defaultValue: "Hudbit",
      options: ["Hudbit", "Trådmerket hudbit"],
      isIndented: false,
      helpText: "Velg om prøven er en vanlig hudbit eller trådmerket",
    },
    {
      id: "primaryMeasurement",
      label: "Måling 1",
      type: "number",
      defaultValue: 0,
      unit: "mm",
      isIndented: false,
      helpText: "Første måling, f.eks. total størrelse",
    },
    {
      id: "lesjonDescription",
      label: "Lesjon/Overflate",
      type: "dropdown",
      defaultValue: "Velavgrenset",
      options: [
        "Velavgrenset",
        "Uregelmessig",
        "Upåfallende",
        "Uskarpt avgrenset",
      ],
      isIndented: false,
      helpText: "Beskrivelse av lesjon, pigmentering eller overflate",
    },
    {
      id: "lesjonMeasurement",
      label: "Måling 2",
      type: "number",
      defaultValue: 0,
      unit: "mm",
      isIndented: false,
      helpText: "Måling knyttet til lesjonen (hvis aktuelt)",
    },
    {
      id: "segmentationType",
      label: "Segmentering",
      type: "dropdown",
      defaultValue: "todeles",
      options: ["todeles", "tverrsnitt"],
      isIndented: false,
      helpText: "Angi om prøven deles eller om tverrsnitt tas",
    },
    {
      id: "segmentCount",
      label: "Antall segmenter",
      type: "number",
      defaultValue: 1,
      isIndented: false,
      helpText: "Antall segmenter hvis segmentering er 'tverrsnitt'",
    },
    {
      id: "extras",
      label: "Ekstra informasjon",
      type: "container",
      optional: true,
      layout: "vertical",
      isIndented: false,
      helpText: "Ytterligere informasjon om hudbitprøven",
      children: [
        {
          id: "tusjes",
          label: "Tusjes",
          type: "checkbox",
          defaultValue: false,
          isIndented: true,
          helpText:
            "Marker dersom prøven skal deles/tusjes i henhold til tegning",
        },
        {
          id: "arrMeasurement",
          label: "Arr (ca.)",
          type: "number",
          defaultValue: 0,
          unit: "mm",
          isIndented: true,
          helpText: "Måling av arr – brukes kun for trådmerket hudbit",
        },
      ],
    },
  ],
};

export const traadvev: TemplateField = {
  id: "traadvev",
  label: "Trådvev",
  type: "container",
  layout: "vertical",
  countField: 1,
  isIndented: false,
  helpText: "Registrering av trådvev-specimen",
  children: [
    {
      id: "vevsbiterCount",
      label: "Antall vevsbiter",
      type: "number",
      isIndented: true,
      defaultValue: 2,
      helpText: "Angi antall trådformede vevsbiter (x)",
    },
    {
      id: "measurement",
      label: "Måling",
      type: "number",
      isIndented: true,
      defaultValue: 1,
      unit: "mm",
      helpText: "Måling (mm) av vevsbitene",
    },
    {
      id: "distribution",
      label: "Fordeling",
      type: "dropdown",
      isIndented: true,
      defaultValue: "fordeles i #1 og #2",
      options: ["i #1", "fordeles i #1 og #2"],
      helpText:
        "Velg om vevsbitene er samlet (i #1) eller fordelt over flere segmenter",
    },
    {
      id: "segments",
      label: "Segmentdetaljer",
      type: "container",
      isIndented: true,
      optional: true,
      conditionalOn: "distribution",
      conditionalValue: "fordeles i #1 og #2",
      layout: "horizontal",
      helpText: "Detaljer om fordelingen over segmenter",
      children: [
        {
          id: "segment1",
          label: "Segment 1",
          type: "container",
          layout: "vertical",
          isIndented: true,
          helpText: "Detaljer om segment 1",
          children: [
            {
              id: "segment1Count",
              label: "Antall biter",
              helpText: "Antall biter",
              type: "number",
              isIndented: true,
              defaultValue: 1,
            },
            {
              id: "segment1Measurement",
              label: "Måling",
              type: "number",
              isIndented: true,
              defaultValue: 1,
              unit: "mm",
              helpText: "Måling av segment 1 i millimeter",
            },
          ],
        },
        {
          id: "segment2",
          label: "Segment 2",
          type: "container",
          layout: "vertical",
          isIndented: true,
          helpText: "Detaljer om segment 2",
          children: [
            {
              id: "segment2Count",
              label: "Antall biter",
              helpText: "Antall biter",
              type: "number",
              isIndented: true,
              defaultValue: 1,
            },
            {
              id: "segment2Measurement",
              label: "Måling",
              type: "number",
              isIndented: true,
              defaultValue: 1,
              unit: "mm",
              helpText: "Måling av segment 2 i millimeter",
            },
          ],
        },
      ],
    },
    {
      id: "colorInfo",
      label: "Fargeinformasjon",
      type: "text",
      isIndented: true,
      defaultValue: "Farges MT, Retic og BB",
      helpText:
        "Oppgi eventuelle fargeanvisninger (f.eks. 'Farges ABPAS' eller 'Farges MT, Retic og BB')",
    },
    {
      id: "fragmented",
      label: "Fragmentert",
      type: "checkbox",
      isIndented: true,
      defaultValue: false,
      helpText: "Marker om vevsbitene er fragmenterte",
    },
  ],
};

export const polypp: TemplateField = {
  id: "polypp",
  label: "Polypp",
  type: "container",
  layout: "vertical",
  countField: 1,
  isIndented: false,
  helpText: "Registrering av polypp-specimen",
  children: [
    {
      id: "polyppType",
      label: "Polypp Type",
      type: "dropdown",
      defaultValue: "Lav, bredbaset",
      options: ["Lav, bredbaset", "Stilket", "Fragmentert"],
      isIndented: false,
      helpText: "Velg polypptype",
    },
    {
      id: "overallMeasurement",
      label: "Overordnet Måling",
      type: "number",
      defaultValue: 0,
      unit: "mm",
      isIndented: false,
      helpText: "Brukes for Lav, bredbaset polypp (f.eks. 'x mm')",
      conditionalOn: "polyppType",
      conditionalValue: ["Lav, bredbaset", "Fragmentert"],
    },
    {
      id: "distribution",
      label: "Fordeling",
      type: "dropdown",
      defaultValue: "seriesnittes i #1",
      options: [
        "seriesnittes i #1",
        "deles med skalker i #1, stilkområde i #2",
      ],
      isIndented: false,
      helpText: "Angi hvordan polyppen behandles",
    },
    {
      id: "stilketDetails",
      label: "Stilket Detaljer",
      type: "container",
      optional: true,
      conditionalOn: "polyppType",
      conditionalValue: "Stilket",
      layout: "vertical",
      isIndented: false,
      helpText: "Detaljer om stilket polypp",
      children: [
        {
          id: "polyppHeadMeasurement",
          label: "Polypphodet",
          type: "number",
          defaultValue: 0,
          unit: "mm",
          isIndented: true,
          helpText: "Måling av polypphodet",
        },
        {
          id: "stilkMeasurement",
          label: "Stilk",
          type: "number",
          defaultValue: 0,
          unit: "mm",
          isIndented: true,
          helpText: "Måling av polyppstilk",
        },
      ],
    },
    {
      id: "fragmentDetails",
      label: "Fragmentdetaljer",
      type: "container",
      optional: true,
      conditionalOn: "polyppType",
      conditionalValue: "Fragmentert",
      layout: "vertical",
      isIndented: false,
      helpText: "Detaljer om fragmentert polypp",
      children: [
        {
          id: "fragmentMeasurements",
          label: "Fragment Målinger",
          type: "container",
          layout: "vertical",
          isIndented: true,
          helpText: "Målinger for fragmentert polypp, angitt som x + x + x mm",
          children: [
            {
              id: "fragMeasurementA",
              label: "Måling A",
              type: "number",
              defaultValue: 0,
              unit: "mm",
              isIndented: true,
              helpText: "Måling A av fragment",
            },
            {
              id: "fragMeasurementB",
              label: "Måling B",
              type: "number",
              defaultValue: 0,
              unit: "mm",
              isIndented: true,
              helpText: "Måling B av fragment",
            },
            {
              id: "fragMeasurementC",
              label: "Måling C",
              type: "number",
              defaultValue: 0,
              unit: "mm",
              isIndented: true,
              helpText: "Måling C av fragment",
            },
          ],
        },
        {
          id: "fragmentSegmentation",
          label: "Segmentering for fragmentert polypp",
          type: "dropdown",
          defaultValue: "ingen",
          options: ["ingen", "deles i #2"],
          isIndented: true,
          helpText:
            "Angi om polyppen deles videre (f.eks. 'bit 5+ mm deles i #2')",
        },
      ],
    },
    {
      id: "additionalNotes",
      label: "Ekstra Notater",
      type: "text",
      defaultValue: "",
      isIndented: false,
      helpText: "Eventuelle ekstra kommentarer",
    },
  ],
};