import { TemplateField } from "../interfaces/iTemplateField";

export const polypp: TemplateField = {
  id: "polypp",
  label: "Polypp",
  type: "container",
  layout: "vertical",
  countField: 1,
  isIndented: false,
  helpText: "Registrering av polypp-specimen",
  children: [
    {
      id: "polyppType",
      label: "Polypp Type",
      type: "dropdown",
      defaultValue: "Lav, bredbaset",
      options: ["Lav, bredbaset", "Stilket", "Fragmentert"],
      isIndented: false,
      helpText: "Velg polypptype",
    },
    {
      id: "overallMeasurement",
      label: "Overordnet Måling",
      type: "number",
      defaultValue: 0,
      unit: "mm",
      isIndented: false,
      helpText: "Brukes for Lav, bredbaset polypp (f.eks. 'x mm')",
      conditionalOn: "polyppType",
      conditionalValue: ["Lav, bredbaset", "Fragmentert"],
    },
    {
      id: "distribution",
      label: "Fordeling",
      type: "dropdown",
      defaultValue: "seriesnittes i #1",
      options: [
        "seriesnittes i #1",
        "deles med skalker i #1, stilkområde i #2",
        "orienteres i #1",
        "deles i #1 og #2"
      ],
      isIndented: false,
      helpText: "Angi hvordan polyppen behandles",
    },
    {
      id: "stilketDetails",
      label: "Stilket Detaljer",
      type: "container",
      optional: true,
      conditionalOn: "polyppType",
      conditionalValue: "Stilket",
      layout: "vertical",
      isIndented: false,
      helpText: "Detaljer om stilket polypp",
      children: [
        {
          id: "polyppHeadMeasurement",
          label: "Polypphodet",
          type: "number",
          defaultValue: 0,
          unit: "mm",
          isIndented: true,
          helpText: "Måling av polypphodet",
        },
        {
          id: "stilkMeasurement",
          label: "Stilk",
          type: "number",
          defaultValue: 0,
          unit: "mm",
          isIndented: true,
          helpText: "Måling av polyppstilk",
        },
      ],
    },
    {
      id: "fragmentDetails",
      label: "Fragmentdetaljer",
      type: "container",
      optional: true,
      conditionalOn: "polyppType",
      conditionalValue: "Fragmentert",
      layout: "vertical",
      isIndented: false,
      helpText: "Detaljer om fragmentert polypp",
      children: [
        {
          id: "fragmentMeasurements",
          label: "Fragment Målinger",
          type: "container",
          layout: "vertical",
          isIndented: true,
          helpText: "Målinger for fragmentert polypp, angitt som x + x + x mm",
          children: [
            {
              id: "fragMeasurementA",
              label: "Måling A",
              type: "number",
              defaultValue: 0,
              unit: "mm",
              isIndented: true,
              helpText: "Måling A av fragment",
            },
            {
              id: "fragMeasurementB",
              label: "Måling B",
              type: "number",
              defaultValue: 0,
              unit: "mm",
              isIndented: true,
              helpText: "Måling B av fragment",
            },
            {
              id: "fragMeasurementC",
              label: "Måling C",
              type: "number",
              defaultValue: 0,
              unit: "mm",
              isIndented: true,
              helpText: "Måling C av fragment",
            },
          ],
        },
      ],
    },
    {
      id: "additionalNotes",
      label: "Ekstra Notater",
      type: "text",
      defaultValue: "",
      isIndented: false,
      helpText: "Eventuelle ekstra kommentarer",
    },
  ],
};

export const tarmscreening: TemplateField = {
  id: "tarmscreening",
  label: "Tarmscreening",
  type: "container",
  layout: "vertical",
  countField: 1,
  isIndented: false,
  helpText: "Registrering av tarmscreening-specimen",
  children: [
    {
      id: "grynCount",
      label: "Antall Gryn",
      type: "number",
      defaultValue: 1,
      isIndented: false,
      helpText: "Antall gryn i prøven",
    },
    {
      id: "vevsbitCount",
      label: "Antall Vevsbiter",
      type: "number",
      defaultValue: 1,
      isIndented: false,
      helpText: "Antall vevsbiter i prøven",
    },
    {
      id: "proveType",
      label: "Prøvetype",
      type: "dropdown",
      defaultValue: "Biopsi",
      options: ["Biopsi", "Polyppektomi", "Resektat", "Polypp"],
      isIndented: false,
      helpText: "Velg type prøve",
    },
    {
      id: "lengde",
      label: "Lengde",
      type: "number",
      defaultValue: 0,
      unit: "mm",
      isIndented: false,
      helpText: "Lengde på prøven",
    },
    {
      id: "bredde",
      label: "Bredde",
      type: "number",
      defaultValue: 0,
      unit: "mm",
      isIndented: false,
      helpText: "Bredde på prøven",
    },
    {
      id: "hoyde",
      label: "Høyde",
      type: "number",
      defaultValue: 0,
      unit: "mm",
      isIndented: false,
      helpText: "Høyde på prøven",
    },
    {
      id: "lokalisasjon",
      label: "Lokalisasjon",
      type: "dropdown",
      defaultValue: "Colon sigmoideum",
      options: [
        "Ileum", 
        "Cøcum", 
        "Colon ascendens", 
        "Høyre fleksur", 
        "Colon transversum", 
        "Venstre fleksur", 
        "Colon descendens", 
        "Colon sigmoideum", 
        "Rektum"
      ],
      isIndented: false,
      helpText: "Velg anatomisk lokalisasjon",
    },
    {
      id: "lesjonsUtseende",
      label: "Lesjonsutseende",
      type: "dropdown",
      defaultValue: "Polypoid",
      options: [
        "Polypoid", 
        "Flat", 
        "Deprimert/Nedsunket", 
        "Ulcerert",
        "Bredbaset",
        "Stilket"
      ],
      isIndented: false,
      helpText: "Beskriv lesjonens utseende",
    },
    {
      id: "storrelse",
      label: "Størrelse (mm)",
      type: "number",
      defaultValue: 0,
      unit: "mm",
      isIndented: false,
      helpText: "Angi størrelse i millimeter",
    },
    {
      id: "storrelse2",
      label: "Størrelse 2 (mm)",
      type: "number",
      defaultValue: 0,
      unit: "mm",
      isIndented: false,
      helpText: "Angi eventuell andre størrelse i millimeter",
    },
    {
      id: "polyppHeadMeasurement",
      label: "Polypphodet",
      type: "number",
      defaultValue: 0,
      unit: "mm",
      isIndented: false,
      helpText: "Måling av polypphodet",
    },
    {
      id: "stilkMeasurement",
      label: "Stilk",
      type: "number",
      defaultValue: 0,
      unit: "mm",
      isIndented: false,
      helpText: "Måling av polyppstilk",
    },
    {
      id: "fragmentMalinger",
      label: "Fragment Målinger",
      type: "container",
      layout: "vertical",
      isIndented: false,
      helpText: "Målinger for fragmenter",
      children: [
        {
          id: "fragMeasurementA",
          label: "Måling A",
          type: "number",
          defaultValue: 0,
          unit: "mm",
          isIndented: true,
          helpText: "Måling A av fragment",
        },
        {
          id: "fragMeasurementB",
          label: "Måling B",
          type: "number",
          defaultValue: 0,
          unit: "mm",
          isIndented: true,
          helpText: "Måling B av fragment",
        },
        {
          id: "fragMeasurementC",
          label: "Måling C",
          type: "number",
          defaultValue: 0,
          unit: "mm",
          isIndented: true,
          helpText: "Måling C av fragment",
        }
      ]
    },
    {
      id: "komplett",
      label: "fjernet komplett?",
      type: "dropdown",
      defaultValue: "Komplett fjernet",
      options: ["Komplett fjernet", "Ikke komplett fjernet"],
      isIndented: false,
      helpText: "Er lesjonen komplett fjernet?",
    },
    {
      id: "niceKlassifikasjon",
      label: "NICE klassifikasjon",
      type: "dropdown",
      defaultValue: "NICE 1",
      options: ["NICE 1", "NICE 2", "NICE 3"],
      isIndented: false,
      helpText: "NICE-klassifikasjon hvis angitt",
    }
  ],
};